server:
     port: 8081

token:
     signing:
          key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
     lifetime: 10m

spring:
     datasource:
          url: jdbc:postgresql://localhost:5432/exlab_tasks_db
          username: postgres
          password: 1234
          driver-class-name: org.postgresql.Driver
     jpa:
          properties:
               hibernate:
                    dialect: org.hibernate.dialect.PostgresPlusDialect
                    show_sql: true
                    ddl-auto: validate
                    format_sql: true
     mail:
          host: smtp.gmail.com
          port: 587
          username: puivan617
          password: sliuhrnbiuqwxjwb
          tls: true
          properties:
               mail:
                    smtp:
                         auth: true
                         starttls:
                              enable: true
               protocol: smtp
               test-connection: false


